name: Build and Run Docker Images

on:
  push:
    branches:
      - android           # Trigger workflow on push to android branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull Docker images
        run: |
          docker pull pritikakade/android_images:android_qa
          docker pull pritikakade/android_images:android_staging
          docker pull pritikakade/android_images:android_prod

      - name: Run Docker images
        run: |
          docker run -d pritikakade/android_images:android_qa
          docker run -d pritikakade/android_images:android_staging
          docker run -d pritikakade/android_images:android_prod

